[tool.poetry]
name = "community-info-collector"
version = "0.1.0"
description = "Reddit community information collector and analyzer"
authors = ["Your Name <your.email@example.com>"]
python = "~3.11"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"